import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const exercises = [
    // PECTORALES
    {
        name: 'Press de banca con barra',
        description: 'Ejercicio fundamental para desarrollar el pecho. Trabaja principalmente los pectorales mayores con énfasis en la fuerza y masa muscular.',
        muscleGroup: 'Pectorales',
        equipment: 'Barra y banco plano',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press banca inclinado con mancuernas',
        description: 'Variante del press de banca que enfatiza la parte superior del pecho. El ángulo inclinado permite un mayor rango de movimiento.',
        muscleGroup: 'Pectorales',
        equipment: 'Mancuernas y banco inclinado',
        difficulty: 'Intermedio',
    },
    {
        name: 'Aperturas en máquina Peck Deck',
        description: 'Ejercicio de aislamiento para el pecho que elimina la participación de los tríceps. Ideal para trabajar la contracción máxima del pectoral.',
        muscleGroup: 'Pectorales',
        equipment: 'Máquina peck deck',
        difficulty: 'Principiante',
    },
    {
        name: 'Cruce de poleas',
        description: 'Ejercicio de aislamiento que permite trabajar el pecho con tensión constante. Excelente para definir y esculpir los pectorales.',
        muscleGroup: 'Pectorales',
        equipment: 'Máquina de poleas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press de banca inclinado con barra',
        description: 'Variante del press de banca con barra en banco inclinado. Enfatiza la porción clavicular del pectoral mayor.',
        muscleGroup: 'Pectorales',
        equipment: 'Barra y banco inclinado',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press de banca con mancuernas',
        description: 'Variante del press de banca que permite mayor rango de movimiento y trabajo unilateral. Ayuda a corregir desbalances musculares.',
        muscleGroup: 'Pectorales',
        equipment: 'Mancuernas y banco plano',
        difficulty: 'Intermedio',
    },
    {
        name: 'Aperturas con mancuernas',
        description: 'Ejercicio de aislamiento clásico para el pecho. Proporciona un excelente estiramiento del pectoral.',
        muscleGroup: 'Pectorales',
        equipment: 'Mancuernas y banco plano',
        difficulty: 'Intermedio',
    },
    {
        name: 'Aperturas inclinadas con mancuernas',
        description: 'Variante de aperturas en banco inclinado que enfatiza la parte superior del pecho.',
        muscleGroup: 'Pectorales',
        equipment: 'Mancuernas y banco inclinado',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press de banca en máquina sentado',
        description: 'Ejercicio guiado que permite trabajar el pecho de forma segura. Ideal para principiantes.',
        muscleGroup: 'Pectorales',
        equipment: 'Máquina de press de pecho',
        difficulty: 'Principiante',
    },
    {
        name: 'Press de banca declinado con barra',
        description: 'Variante del press de banca que enfatiza la porción inferior del pecho.',
        muscleGroup: 'Pectorales',
        equipment: 'Barra y banco declinado',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press de banca declinado con mancuernas',
        description: 'Variante con mancuernas del press declinado. Ofrece mayor rango de movimiento para la parte inferior del pecho.',
        muscleGroup: 'Pectorales',
        equipment: 'Mancuernas y banco declinado',
        difficulty: 'Intermedio',
    },
    {
        name: 'Flexiones',
        description: 'Ejercicio clásico con el propio peso corporal. Trabaja pecho, tríceps y core de forma funcional.',
        muscleGroup: 'Pectorales',
        equipment: 'Peso corporal',
        difficulty: 'Principiante',
    },

    // ESPALDA
    {
        name: 'Remo con mancuerna a una mano',
        description: 'Ejercicio unilateral fundamental para desarrollar el grosor de la espalda. Permite un gran rango de movimiento.',
        muscleGroup: 'Espalda',
        equipment: 'Mancuerna y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Jalón con agarre ancho',
        description: 'Ejercicio clave para desarrollar el ancho de la espalda. Trabaja principalmente los dorsales.',
        muscleGroup: 'Espalda',
        equipment: 'Máquina de poleas',
        difficulty: 'Principiante',
    },
    {
        name: 'Remo en máquina',
        description: 'Ejercicio de remo sentado que trabaja el grosor de la espalda media.',
        muscleGroup: 'Espalda',
        equipment: 'Máquina de remo',
        difficulty: 'Principiante',
    },
    {
        name: 'Jalón al pecho con agarre cerrado',
        description: 'Variante del jalón que enfatiza la parte central de la espalda.',
        muscleGroup: 'Espalda',
        equipment: 'Máquina de poleas',
        difficulty: 'Principiante',
    },
    {
        name: 'Remo con barra',
        description: 'Ejercicio compuesto fundamental para construir masa en la espalda. Trabaja toda la cadena posterior.',
        muscleGroup: 'Espalda',
        equipment: 'Barra',
        difficulty: 'Intermedio',
    },
    {
        name: 'Jalón tras nuca',
        description: 'Variante del jalón que trabaja la espalda desde un ángulo diferente.',
        muscleGroup: 'Espalda',
        equipment: 'Máquina de poleas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Jalón al pecho con agarre invertido',
        description: 'Variante del jalón con agarre supinado que involucra más los bíceps.',
        muscleGroup: 'Espalda',
        equipment: 'Máquina de poleas',
        difficulty: 'Principiante',
    },
    {
        name: 'Jalón en polea con cuerda',
        description: 'Variante del jalón usando cuerda que permite un agarre neutro.',
        muscleGroup: 'Espalda',
        equipment: 'Máquina de poleas con cuerda',
        difficulty: 'Intermedio',
    },
    {
        name: 'Remo en barra T',
        description: 'Ejercicio de remo que permite manejar buen peso para desarrollar grosor en la espalda.',
        muscleGroup: 'Espalda',
        equipment: 'Barra T',
        difficulty: 'Intermedio',
    },
    {
        name: 'Remo inclinado con barra agarre supinado',
        description: 'Variante del remo con barra usando agarre supinado.',
        muscleGroup: 'Espalda',
        equipment: 'Barra',
        difficulty: 'Intermedio',
    },
    {
        name: 'Elevaciones en barra fija',
        description: 'Ejercicio con peso corporal que desarrolla fuerza y masa en la espalda.',
        muscleGroup: 'Espalda',
        equipment: 'Barra fija',
        difficulty: 'Intermedio',
    },
    {
        name: 'Elevaciones tras nuca en barra fija',
        description: 'Variante de dominadas llevando la barra detrás de la cabeza.',
        muscleGroup: 'Espalda',
        equipment: 'Barra fija',
        difficulty: 'Avanzado',
    },
    {
        name: 'Elevaciones en barra con agarre supinado',
        description: 'Dominadas con agarre supinado que involucran más los bíceps.',
        muscleGroup: 'Espalda',
        equipment: 'Barra fija',
        difficulty: 'Intermedio',
    },
    {
        name: 'Jalón dorsal con brazos rectos',
        description: 'Ejercicio de aislamiento para los dorsales manteniendo los brazos rectos.',
        muscleGroup: 'Espalda',
        equipment: 'Máquina de poleas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Remo inclinado con mancuernas',
        description: 'Ejercicio de remo bilateral con mancuernas.',
        muscleGroup: 'Espalda',
        equipment: 'Mancuernas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Pullover con mancuerna',
        description: 'Ejercicio que trabaja dorsales y pecho simultáneamente.',
        muscleGroup: 'Espalda',
        equipment: 'Mancuerna y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Pullover con barra',
        description: 'Variante del pullover usando barra.',
        muscleGroup: 'Espalda',
        equipment: 'Barra y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Peso muerto con barra',
        description: 'Uno de los ejercicios más completos. Trabaja toda la cadena posterior incluyendo espalda baja, glúteos e isquiotibiales.',
        muscleGroup: 'Espalda',
        equipment: 'Barra',
        difficulty: 'Avanzado',
    },
    {
        name: 'Peso muerto sumo con barra',
        description: 'Variante del peso muerto con postura amplia que enfatiza más los glúteos.',
        muscleGroup: 'Espalda',
        equipment: 'Barra',
        difficulty: 'Avanzado',
    },
    {
        name: 'Peso muerto con barra hexagonal',
        description: 'Variante del peso muerto usando barra hexagonal que reduce estrés en la espalda baja.',
        muscleGroup: 'Espalda',
        equipment: 'Barra hexagonal',
        difficulty: 'Intermedio',
    },
    {
        name: 'Peso muerto con mancuernas',
        description: 'Variante del peso muerto usando mancuernas.',
        muscleGroup: 'Espalda',
        equipment: 'Mancuernas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Encogimiento de hombros con barra',
        description: 'Ejercicio para desarrollar los trapecios superiores.',
        muscleGroup: 'Espalda',
        equipment: 'Barra',
        difficulty: 'Principiante',
    },
    {
        name: 'Encogimiento de hombros con mancuernas',
        description: 'Variante de encogimientos usando mancuernas.',
        muscleGroup: 'Espalda',
        equipment: 'Mancuernas',
        difficulty: 'Principiante',
    },

    // HOMBROS
    {
        name: 'Press de hombro con mancuernas',
        description: 'Ejercicio fundamental para desarrollar los deltoides. Permite un rango de movimiento natural.',
        muscleGroup: 'Hombros',
        equipment: 'Mancuernas y banco con respaldo',
        difficulty: 'Intermedio',
    },
    {
        name: 'Elevación lateral con mancuernas',
        description: 'Ejercicio de aislamiento para el deltoides medio. Crea el ancho de los hombros.',
        muscleGroup: 'Hombros',
        equipment: 'Mancuernas',
        difficulty: 'Principiante',
    },
    {
        name: 'Elevación frontal con mancuernas',
        description: 'Ejercicio de aislamiento para el deltoides anterior.',
        muscleGroup: 'Hombros',
        equipment: 'Mancuernas',
        difficulty: 'Principiante',
    },
    {
        name: 'Cruces inversos en polea alta',
        description: 'Ejercicio para trabajar el deltoides posterior.',
        muscleGroup: 'Hombros',
        equipment: 'Máquina de poleas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press de hombros en Máquina Smith',
        description: 'Ejercicio de press guiado que permite trabajar con buen peso de forma segura.',
        muscleGroup: 'Hombros',
        equipment: 'Máquina Smith',
        difficulty: 'Intermedio',
    },
    {
        name: 'Remo alto con barra',
        description: 'Ejercicio compuesto que trabaja deltoides y trapecios.',
        muscleGroup: 'Hombros',
        equipment: 'Barra',
        difficulty: 'Intermedio',
    },
    {
        name: 'Elevaciones posteriores para hombros "Pájaro"',
        description: 'Ejercicio de aislamiento para el deltoides posterior.',
        muscleGroup: 'Hombros',
        equipment: 'Mancuernas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Elevación lateral con cable a una mano',
        description: 'Variante de elevaciones laterales usando cable.',
        muscleGroup: 'Hombros',
        equipment: 'Máquina de poleas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press Militar con mancuernas',
        description: 'Ejercicio de press de hombros de pie con mancuernas.',
        muscleGroup: 'Hombros',
        equipment: 'Mancuernas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press Militar',
        description: 'Press de hombros de pie con barra, ejercicio clásico de fuerza.',
        muscleGroup: 'Hombros',
        equipment: 'Barra',
        difficulty: 'Intermedio',
    },
    {
        name: 'Elevaciones frontales con cable a una mano',
        description: 'Variante de elevaciones frontales usando cable.',
        muscleGroup: 'Hombros',
        equipment: 'Máquina de poleas',
        difficulty: 'Principiante',
    },
    {
        name: 'Elevaciones frontales con barra',
        description: 'Ejercicio de elevaciones frontales usando barra.',
        muscleGroup: 'Hombros',
        equipment: 'Barra',
        difficulty: 'Principiante',
    },
    {
        name: 'Press militar sentado con barra',
        description: 'Ejercicio compuesto clásico para hombros sentado.',
        muscleGroup: 'Hombros',
        equipment: 'Barra y banco con respaldo',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press tras nuca sentado',
        description: 'Variante del press militar llevando la barra detrás de la cabeza.',
        muscleGroup: 'Hombros',
        equipment: 'Barra y banco con respaldo',
        difficulty: 'Avanzado',
    },
    {
        name: 'Press militar de pie',
        description: 'Press de hombros de pie con barra.',
        muscleGroup: 'Hombros',
        equipment: 'Barra',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press militar de pie tras nuca',
        description: 'Press de pie llevando la barra detrás de la cabeza.',
        muscleGroup: 'Hombros',
        equipment: 'Barra',
        difficulty: 'Avanzado',
    },
    {
        name: 'Elevación frontal con mancuernas alternas agarre neutro',
        description: 'Elevaciones frontales alternando brazos con agarre neutro.',
        muscleGroup: 'Hombros',
        equipment: 'Mancuernas',
        difficulty: 'Principiante',
    },
    {
        name: 'Elevación frontal con un brazo en polea baja agarre neutro',
        description: 'Elevaciones frontales unilaterales con cable.',
        muscleGroup: 'Hombros',
        equipment: 'Máquina de poleas',
        difficulty: 'Principiante',
    },
    {
        name: 'Elevación frontal con mancuerna a dos manos',
        description: 'Elevaciones frontales sosteniendo una mancuerna con ambas manos.',
        muscleGroup: 'Hombros',
        equipment: 'Mancuerna',
        difficulty: 'Principiante',
    },

    // BÍCEPS
    {
        name: 'Curl con barra',
        description: 'Ejercicio fundamental para desarrollar los bíceps. Permite manejar buen peso.',
        muscleGroup: 'Bíceps',
        equipment: 'Barra',
        difficulty: 'Principiante',
    },
    {
        name: 'Curl alterno con mancuernas',
        description: 'Ejercicio unilateral que permite enfocarse en cada brazo individualmente.',
        muscleGroup: 'Bíceps',
        equipment: 'Mancuernas',
        difficulty: 'Principiante',
    },
    {
        name: 'Curl con cuerda en polea',
        description: 'Ejercicio de curl usando cuerda en polea.',
        muscleGroup: 'Bíceps',
        equipment: 'Máquina de poleas con cuerda',
        difficulty: 'Principiante',
    },
    {
        name: 'Curl con barra EZ',
        description: 'Variante del curl con barra usando barra EZ que reduce estrés en las muñecas.',
        muscleGroup: 'Bíceps',
        equipment: 'Barra EZ',
        difficulty: 'Principiante',
    },
    {
        name: 'Curl de predicador con barra EZ',
        description: 'Ejercicio de curl en banco predicador que aísla los bíceps.',
        muscleGroup: 'Bíceps',
        equipment: 'Barra EZ y banco predicador',
        difficulty: 'Intermedio',
    },
    {
        name: 'Curl alterno de martillo con mancuernas',
        description: 'Variante del curl que trabaja el braquial y braquiorradial.',
        muscleGroup: 'Bíceps',
        equipment: 'Mancuernas',
        difficulty: 'Principiante',
    },
    {
        name: 'Curl inclinado con mancuernas',
        description: 'Curl en banco inclinado que proporciona mayor estiramiento del bíceps.',
        muscleGroup: 'Bíceps',
        equipment: 'Mancuernas y banco inclinado',
        difficulty: 'Intermedio',
    },
    {
        name: 'Curl concentrado con mancuernas',
        description: 'Ejercicio de aislamiento puro para el bíceps.',
        muscleGroup: 'Bíceps',
        equipment: 'Mancuerna y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Curl de cable en polea baja a una mano',
        description: 'Curl unilateral usando cable en polea baja.',
        muscleGroup: 'Bíceps',
        equipment: 'Máquina de poleas',
        difficulty: 'Principiante',
    },
    {
        name: 'Curl de cable con barra recta en polea baja',
        description: 'Curl bilateral usando barra recta en cable.',
        muscleGroup: 'Bíceps',
        equipment: 'Máquina de poleas',
        difficulty: 'Principiante',
    },
    {
        name: 'Curl de cable en polea alta de pie',
        description: 'Curl usando polea alta que cambia el ángulo de trabajo.',
        muscleGroup: 'Bíceps',
        equipment: 'Máquina de poleas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Curl de muñeca con barra sentado',
        description: 'Ejercicio para fortalecer los antebrazos.',
        muscleGroup: 'Bíceps',
        equipment: 'Barra y banco',
        difficulty: 'Principiante',
    },
    {
        name: 'Extensión de muñeca con barra sentado',
        description: 'Ejercicio para trabajar los extensores del antebrazo.',
        muscleGroup: 'Bíceps',
        equipment: 'Barra y banco',
        difficulty: 'Principiante',
    },
    {
        name: 'Curl de barra invertido',
        description: 'Curl con agarre pronado que trabaja braquiorradial y antebrazos.',
        muscleGroup: 'Bíceps',
        equipment: 'Barra',
        difficulty: 'Intermedio',
    },

    // TRÍCEPS
    {
        name: 'Extensión de tríceps tumbado',
        description: 'Ejercicio clásico para desarrollar masa en los tríceps.',
        muscleGroup: 'Tríceps',
        equipment: 'Barra y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Extensión de tríceps en polea',
        description: 'Ejercicio de aislamiento que mantiene tensión constante en los tríceps.',
        muscleGroup: 'Tríceps',
        equipment: 'Máquina de poleas',
        difficulty: 'Principiante',
    },
    {
        name: 'Extensión de tríceps en polea con cuerda',
        description: 'Variante con cuerda que permite mayor rango de movimiento.',
        muscleGroup: 'Tríceps',
        equipment: 'Máquina de poleas con cuerda',
        difficulty: 'Principiante',
    },
    {
        name: 'Extensión de tríceps con mancuernas por encima de la cabeza',
        description: 'Ejercicio overhead que trabaja especialmente la cabeza larga del tríceps.',
        muscleGroup: 'Tríceps',
        equipment: 'Mancuerna',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press Banca con agarre cerrado',
        description: 'Ejercicio compuesto que enfatiza los tríceps.',
        muscleGroup: 'Tríceps',
        equipment: 'Barra y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Patadas traseras',
        description: 'Ejercicio de aislamiento para tríceps.',
        muscleGroup: 'Tríceps',
        equipment: 'Mancuernas',
        difficulty: 'Principiante',
    },
    {
        name: 'Extensión de tríceps con cable de agarre inverso',
        description: 'Variante de extensiones con agarre inverso.',
        muscleGroup: 'Tríceps',
        equipment: 'Máquina de poleas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Extensión de tríceps con cable a una mano',
        description: 'Extensión unilateral usando cable.',
        muscleGroup: 'Tríceps',
        equipment: 'Máquina de poleas',
        difficulty: 'Principiante',
    },
    {
        name: 'Extensión de tríceps con cable a una mano agarre supinado',
        description: 'Variante unilateral con agarre supinado.',
        muscleGroup: 'Tríceps',
        equipment: 'Máquina de poleas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Extensión de tríceps con mancuernas tumbado',
        description: 'Variante de extensiones tumbado usando mancuernas.',
        muscleGroup: 'Tríceps',
        equipment: 'Mancuernas y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Press francés sentado con barra',
        description: 'Ejercicio overhead sentado con barra.',
        muscleGroup: 'Tríceps',
        equipment: 'Barra y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Fondos en banco',
        description: 'Ejercicio con peso corporal para tríceps.',
        muscleGroup: 'Tríceps',
        equipment: 'Banco',
        difficulty: 'Principiante',
    },
    {
        name: 'Fondos en barras paralelas',
        description: 'Ejercicio compuesto con peso corporal que desarrolla fuerza y masa en tríceps.',
        muscleGroup: 'Tríceps',
        equipment: 'Barras paralelas',
        difficulty: 'Intermedio',
    },

    // ABDOMINALES
    {
        name: 'Crunch',
        description: 'Ejercicio básico para trabajar el recto abdominal.',
        muscleGroup: 'Abdominales',
        equipment: 'Peso corporal',
        difficulty: 'Principiante',
    },
    {
        name: 'Crunch oblicuo',
        description: 'Ejercicio que trabaja los oblicuos y los abdominales laterales.',
        muscleGroup: 'Abdominales',
        equipment: 'Peso corporal',
        difficulty: 'Principiante',
    },
    {
        name: 'Abdominales en máquina',
        description: 'Ejercicio de abdominales usando máquina con resistencia.',
        muscleGroup: 'Abdominales',
        equipment: 'Máquina de abdominales',
        difficulty: 'Principiante',
    },
    {
        name: 'Abdominales con cuerda en polea alta',
        description: 'Ejercicio de abdominales usando cable en polea alta.',
        muscleGroup: 'Abdominales',
        equipment: 'Máquina de poleas con cuerda',
        difficulty: 'Intermedio',
    },
    {
        name: 'Plancha',
        description: 'Ejercicio isométrico que trabaja todo el core.',
        muscleGroup: 'Abdominales',
        equipment: 'Peso corporal',
        difficulty: 'Principiante',
    },
    {
        name: 'Elevación de piernas',
        description: 'Ejercicio avanzado que trabaja la parte inferior del abdomen.',
        muscleGroup: 'Abdominales',
        equipment: 'Barra fija',
        difficulty: 'Avanzado',
    },
    {
        name: 'Encogimientos de rodillas para abdominales',
        description: 'Ejercicio que trabaja la parte inferior del abdomen.',
        muscleGroup: 'Abdominales',
        equipment: 'Peso corporal',
        difficulty: 'Intermedio',
    },
    {
        name: 'Abdominales con brazos estirados',
        description: 'Variante de crunch con los brazos extendidos.',
        muscleGroup: 'Abdominales',
        equipment: 'Peso corporal',
        difficulty: 'Intermedio',
    },
    {
        name: 'Plancha con flexión',
        description: 'Variante dinámica de la plancha.',
        muscleGroup: 'Abdominales',
        equipment: 'Peso corporal',
        difficulty: 'Intermedio',
    },

    // PIERNAS
    {
        name: 'Sentadilla',
        description: 'El rey de los ejercicios de piernas. Trabaja cuádriceps, glúteos e isquiotibiales.',
        muscleGroup: 'Piernas',
        equipment: 'Barra y rack',
        difficulty: 'Intermedio',
    },
    {
        name: 'Prensa de piernas',
        description: 'Ejercicio de máquina que permite trabajar las piernas con cargas pesadas de forma segura.',
        muscleGroup: 'Piernas',
        equipment: 'Máquina de prensa',
        difficulty: 'Principiante',
    },
    {
        name: 'Extensión de piernas',
        description: 'Ejercicio de aislamiento para los cuádriceps.',
        muscleGroup: 'Piernas',
        equipment: 'Máquina de extensión',
        difficulty: 'Principiante',
    },
    {
        name: 'Zancada',
        description: 'Ejercicio unilateral que trabaja cuádriceps, glúteos e isquiotibiales.',
        muscleGroup: 'Piernas',
        equipment: 'Mancuernas o barra',
        difficulty: 'Intermedio',
    },
    {
        name: 'Curl de pierna tumbado',
        description: 'Ejercicio de aislamiento para los isquiotibiales.',
        muscleGroup: 'Piernas',
        equipment: 'Máquina de curl',
        difficulty: 'Principiante',
    },
    {
        name: 'Sentadilla Hack',
        description: 'Variante de sentadilla en máquina hack.',
        muscleGroup: 'Piernas',
        equipment: 'Máquina hack squat',
        difficulty: 'Intermedio',
    },
    {
        name: 'Curl de piernas sentado',
        description: 'Variante de curl de piernas en posición sentada.',
        muscleGroup: 'Piernas',
        equipment: 'Máquina de curl sentado',
        difficulty: 'Principiante',
    },
    {
        name: 'Extensión a una pierna',
        description: 'Extensión de piernas unilateral.',
        muscleGroup: 'Piernas',
        equipment: 'Máquina de extensión',
        difficulty: 'Principiante',
    },
    {
        name: 'Sentadilla frontal',
        description: 'Variante de sentadilla con la barra al frente.',
        muscleGroup: 'Piernas',
        equipment: 'Barra y rack',
        difficulty: 'Avanzado',
    },
    {
        name: 'Peso muerto rumano con mancuernas',
        description: 'Ejercicio que enfatiza los isquiotibiales y glúteos.',
        muscleGroup: 'Piernas',
        equipment: 'Mancuernas',
        difficulty: 'Intermedio',
    },
    {
        name: 'Peso muerto rumano con barra',
        description: 'Variante del peso muerto que enfatiza la cadena posterior.',
        muscleGroup: 'Piernas',
        equipment: 'Barra',
        difficulty: 'Intermedio',
    },
    {
        name: 'Sentadilla Goblet con mancuerna',
        description: 'Sentadilla sosteniendo una mancuerna al pecho.',
        muscleGroup: 'Piernas',
        equipment: 'Mancuerna',
        difficulty: 'Principiante',
    },
    {
        name: 'Salto Rodillas al Pecho',
        description: 'Ejercicio pliométrico para piernas.',
        muscleGroup: 'Piernas',
        equipment: 'Peso corporal',
        difficulty: 'Intermedio',
    },
    {
        name: 'Burpees',
        description: 'Ejercicio de cuerpo completo que incluye trabajo de piernas.',
        muscleGroup: 'Piernas',
        equipment: 'Peso corporal',
        difficulty: 'Intermedio',
    },
    {
        name: 'Sentadillas con propio peso',
        description: 'Sentadilla básica con peso corporal.',
        muscleGroup: 'Piernas',
        equipment: 'Peso corporal',
        difficulty: 'Principiante',
    },
    {
        name: 'Sentadilla búlgara con barra',
        description: 'Sentadilla unilateral con pie trasero elevado.',
        muscleGroup: 'Piernas',
        equipment: 'Barra y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Sentadilla búlgara con propio peso',
        description: 'Variante de sentadilla búlgara sin peso adicional.',
        muscleGroup: 'Piernas',
        equipment: 'Peso corporal',
        difficulty: 'Principiante',
    },
    {
        name: 'Sentadilla con salto',
        description: 'Sentadilla pliométrica con salto.',
        muscleGroup: 'Piernas',
        equipment: 'Peso corporal',
        difficulty: 'Intermedio',
    },
    {
        name: 'Sentadilla isométrica apoyado sobre la pared',
        description: 'Ejercicio isométrico de sentadilla contra la pared.',
        muscleGroup: 'Piernas',
        equipment: 'Peso corporal',
        difficulty: 'Principiante',
    },
    {
        name: 'Peso muerto a una pierna',
        description: 'Peso muerto unilateral que trabaja equilibrio y estabilidad.',
        muscleGroup: 'Piernas',
        equipment: 'Peso corporal',
        difficulty: 'Intermedio',
    },
    {
        name: 'Sentadilla sumo con kettlebell',
        description: 'Sentadilla con postura amplia usando kettlebell.',
        muscleGroup: 'Piernas',
        equipment: 'Kettlebell',
        difficulty: 'Intermedio',
    },
    {
        name: 'Ejercicio "buenos días" con barra',
        description: 'Ejercicio de bisagra de cadera que trabaja la cadena posterior.',
        muscleGroup: 'Piernas',
        equipment: 'Barra',
        difficulty: 'Intermedio',
    },
    {
        name: 'Puente con propio peso',
        description: 'Ejercicio para glúteos usando peso corporal.',
        muscleGroup: 'Piernas',
        equipment: 'Peso corporal',
        difficulty: 'Principiante',
    },
    {
        name: 'Puentes a una pierna',
        description: 'Variante unilateral del puente de glúteos.',
        muscleGroup: 'Piernas',
        equipment: 'Peso corporal',
        difficulty: 'Intermedio',
    },
    {
        name: 'Puente con bandas',
        description: 'Puente de glúteos usando banda de resistencia.',
        muscleGroup: 'Piernas',
        equipment: 'Banda elástica',
        difficulty: 'Principiante',
    },
    {
        name: 'Elevaciones de cadera con máquina Smith',
        description: 'Hip thrust usando máquina Smith.',
        muscleGroup: 'Piernas',
        equipment: 'Máquina Smith y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Elevaciones de cadera con barra',
        description: 'Hip thrust con barra libre.',
        muscleGroup: 'Piernas',
        equipment: 'Barra y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Abducción de cadera con máquina',
        description: 'Ejercicio de abducción en máquina para glúteos.',
        muscleGroup: 'Piernas',
        equipment: 'Máquina de abducción',
        difficulty: 'Principiante',
    },
    {
        name: 'Abducción con polea',
        description: 'Abducción de cadera usando cable.',
        muscleGroup: 'Piernas',
        equipment: 'Máquina de poleas',
        difficulty: 'Principiante',
    },
    {
        name: 'Step Up con mancuernas',
        description: 'Subidas a banco con mancuernas.',
        muscleGroup: 'Piernas',
        equipment: 'Mancuernas y banco',
        difficulty: 'Intermedio',
    },
    {
        name: 'Elevaciones de rodilla',
        description: 'Ejercicio de elevación de rodillas de pie.',
        muscleGroup: 'Piernas',
        equipment: 'Peso corporal',
        difficulty: 'Principiante',
    },
    {
        name: 'Columpios con kettlebell',
        description: 'Ejercicio balístico con kettlebell que trabaja cadena posterior.',
        muscleGroup: 'Piernas',
        equipment: 'Kettlebell',
        difficulty: 'Intermedio',
    },

    // GEMELOS
    {
        name: 'Elevación de gemelos sentado',
        description: 'Ejercicio que trabaja el sóleo, la porción profunda de la pantorrilla.',
        muscleGroup: 'Gemelos',
        equipment: 'Máquina de gemelos sentado',
        difficulty: 'Principiante',
    },
    {
        name: 'Elevación de gemelos de pie',
        description: 'Ejercicio que trabaja principalmente el gastrocnemio.',
        muscleGroup: 'Gemelos',
        equipment: 'Máquina de gemelos de pie',
        difficulty: 'Principiante',
    },
]

async function main() {
    console.log('🌱 Iniciando seed de ejercicios...')

    for (const exercise of exercises) {
        await prisma.exercise.upsert({
            where: { name: exercise.name },
            update: exercise,
            create: exercise,
        })
    }

    console.log(`✅ ${exercises.length} ejercicios cargados exitosamente`)
}

main()
    .catch((e) => {
        console.error('❌ Error al cargar ejercicios:', e)
        process.exit(1)
    })
    .finally(async () => {
        await prisma.$disconnect()
    })
